#!/bin/bash

# a basic setup script for starting up a new mac

set -euo pipefail

if [[ "$(uname)" != "Darwin" ]] ; then
    echo "this setup script only supports macOS"
    exit 1
fi

if [ -z "${DOTPATH:-}" ] ; then
    echo "DOTPATH is not set"
    exit 1
fi

brew_install_if_missing() {
    local cmd="$1"
    local pkg="${2:-$1}"
    if ! command -v "$cmd" >/dev/null ; then
        echo "$cmd not found, installing"
        brew install "$pkg"
    else
        echo "$cmd already installed"
    fi
}

# install xcode command line tools if not installed
xcode-select -p >/dev/null 2>&1 || xcode-select --install

echo "looking for homebrew"
if ! command -v brew >/dev/null ; then
    echo "installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    # exit here, because you need to run the commands after installation for setup
    # dont necessarily script these
    # echo >> /Users/aaron/.zprofile
    # echo 'eval "$(/opt/homebrew/bin/brew shellenv zsh)"' >> /Users/aaron/.zprofile
    # eval "$(/opt/homebrew/bin/brew shellenv zsh)"
else
    echo "updating homebrew"
    brew update
fi

# create top-level files --- TODO these should be more like an append. and ideally it would take in the appropriate file, since bashrc or bash_profile or .bashrc.user could be used
# NOTE
# inputrc is handled by a path variable in the bashrc

#############################
######    CLI TOOLS    ######
#############################
brew_install_if_missing tmux
brew_install_if_missing starship
brew_install_if_missing fzf
brew_install_if_missing fd
brew_install_if_missing nvim neovim

#############################
########     TMUX     #######
#############################
if [ ! -f "$HOME/.tmux.conf" ]; then
    echo "adding .tmux.conf"
    echo "source-file $DOTPATH/.tmux.conf" > "$HOME/.tmux.conf"
fi

#############################
#########    ZSH    #########
#############################
# Create zshrc
if [ ! -f "$HOME/.zshrc" ]; then
    echo "adding .zshrc"
    echo "source $DOTPATH/.zshrc" > "$HOME/.zshrc"
fi

# if [ ! -f $HOME/.bash_profile ]; then
#   echo "adding .bash_profile"
#     echo "source $DOTPATH/.bashrc" > $HOME/.bash_profile
# fi

#############################
#########    VIM    #########
#############################
if [ ! -f "$HOME/.vimrc" ]; then
    echo "adding .vimrc"
    echo "source $DOTPATH/.vimrc" > "$HOME/.vimrc"
fi

echo "dont forget to add a nerdfont - like hack nerdfont - then set to your profile in iterm"

# for using neovim
# create a file:
# ~/.config/nvim/init.vim (that will be like your .vimrc, you’ll paste all your custom config at this file)
#that file should have the following to just leave .vimrc as config

# set runtimepath^=~/.vim runtimepath+=~/.vim/after
# let &packpath = &runtimepath
# source ~/.vimrc
if [ ! -f "$HOME/.config/nvim/init.vim" ]; then
    mkdir -p "$HOME/.config/nvim" && touch "$HOME/.config/nvim/init.vim"
    printf "set runtimepath^=~/.vim runtimepath+=~/.vim/after\nlet &packpath = &runtimepath\nsource ~/.vimrc" >> "$HOME/.config/nvim/init.vim"
fi

# install vundle
echo "looking for vundle"
if [ ! -d "$HOME/.vim/bundle/Vundle.vim" ]; then
    echo "installing vundle"
    git clone -q https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
    # go to  ~/dotfiles/.vim.plugins and :PluginInstall
else
    echo "vundle already installed"
fi


#############################
#########    GIT    #########
#############################
# Create the gitconfig mapping
if grep -q "dotfiles/.gitconfig" "$HOME/.gitconfig" 2>/dev/null ; then
    echo "gitconfig already configured"
else
    echo "adding dotfiles gitconfig to gitconfig path"
    printf "[include]\n\tpath = ~/dotfiles/.gitconfig\n" >> "$HOME/.gitconfig"
fi

if [ ! -f "$HOME/.git-completion.bash" ]; then
    echo "installing git-completion script"
    curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -o ~/.git-completion.bash
else
    echo "git-completion script already installed"
fi



#############################
########    PYTHON    #######
#############################
if ! command -v uv >/dev/null ; then
    read -p "uv not found. install via brew? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]] ; then
        brew install uv
    else
        echo "skipping uv install"
    fi
else
    echo "uv already installed"
fi


# inputrc doesnt work in ipython & ipdb
# run `ipython profile create`
# ```
# set the following
## Shortcut style to use at the prompt. 'vi' or 'emacs'.
#  Default: 'emacs'
# c.TerminalInteractiveShell.editing_mode = "vi"

## Set the editor used by IPython (default to $EDITOR/vi/notepad).
#  Default: 'nvim'
# c.TerminalInteractiveShell.editor = "nvim"
# ```
# theres more i havent explored

# vim: ft=sh
